### ISSUE TITLE
hit a panic: runtime error

### ISSUE THREAD

**Issue by ryao-mdanderson** [singularityhub/docker2singularity#106]
Hello:

I created a docker image rstudio-4.0.4-20211017, I wanted to converted it to a singularity file. I used the following method and it worked perfect for me in past, but today it failed with the error message:

docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm quay.io/singularity/docker2singularity rstudio-4.0.4-20211017

Image Format: squashfs
Docker Image: rstudio-4.0.4-20211017

Inspected Size: 2883 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
(3/10) Creating labels...
(4/10) Adding run script...
(5/10) Setting ENV variables...
(6/10) Adding mount points...
(7/10) Fixing permissions...
(8/10) Stopping and removing the container...
(9/10) Building squashfs container...
INFO:    Starting build...
INFO:    Creating SIF file...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x5635685b337a]

goroutine 1 [running]:
github.com/sylabs/sif/v2/pkg/sif.CreateContainerAtPath(0x7ffccd453e35, 0x37, 0xc000586b80, 0x1, 0x1, 0xc0004fef00, 0x2, 0x4)
	github.com/sylabs/sif/v2@v2.0.0/pkg/sif/create.go:269 +0x17a
github.com/sylabs/singularity/internal/pkg/build/assemblers.createSIF(0x7ffccd453e35, 0x37, 0xc0003b0000, 0xc00016c690, 0x2d, 0x0, 0x563568cd707e, 0x5, 0x0, 0x0)
	github.com/sylabs/singularity@v0.0.0/internal/pkg/build/assemblers/sif.go:121 +0x809
github.com/sylabs/singularity/internal/pkg/build/assemblers.(*SIFAssembler).Assemble(0xc000388de0, 0xc0003b0000, 0x7ffccd453e35, 0x37, 0x0, 0x0)
	github.com/sylabs/singularity@v0.0.0/internal/pkg/build/assemblers/sif.go:212 +0x600
github.com/sylabs/singularity/internal/pkg/build.(*stage).Assemble(...)
	github.com/sylabs/singularity@v0.0.0/internal/pkg/build/stage.go:42
github.com/sylabs/singularity/internal/pkg/build.(*Build).Full(0xc0001aa180, 0x5635694e2980, 0xc000042058, 0x0, 0x0)
	github.com/sylabs/singularity@v0.0.0/internal/pkg/build/build.go:466 +0xb85
github.com/sylabs/singularity/cmd/internal/cli.runBuildLocal(0x5635694e2980, 0xc000042058, 0x563569d6e8a0, 0x7ffccd453e35, 0x37, 0x7ffccd453e6d, 0x39)
	github.com/sylabs/singularity@v0.0.0/cmd/internal/cli/build_linux.go:348 +0x840
github.com/sylabs/singularity/cmd/internal/cli.runBuild(0x563569d6e8a0, 0xc000264140, 0x2, 0x2)
	github.com/sylabs/singularity@v0.0.0/cmd/internal/cli/build_linux.go:134 +0x34a
github.com/spf13/cobra.(*Command).execute(0x563569d6e8a0, 0xc00003c0e0, 0x2, 0x2, 0x563569d6e8a0, 0xc00003c0e0)
	github.com/spf13/cobra@v1.2.1/command.go:860 +0x2ac
github.com/spf13/cobra.(*Command).ExecuteC(0x563569d792a0, 0x563569495578, 0xc0000a3860, 0xc00031dfb0)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.2.1/command.go:895
github.com/sylabs/singularity/cmd/internal/cli.ExecuteSingularity()
	github.com/sylabs/singularity@v0.0.0/cmd/internal/cli/singularity.go:430 +0x20e
main.main()
	github.com/sylabs/singularity@v0.0.0/cmd/singularity/cli.go:19 +0x52

Today, before seeing the above error message,  I tried the above command and hit an error:
FATAL:   While performing build: while creating SIF: while creating container: writing data object for SIF file: copying data object file to SIF file: write /tmp/rstudio-4.0.4-20211017-2021-10-18-ae6bf9b2ebd6.sif: no space left on device

So, I used the command "docker system prune -a" to remove exited containers and unused images. I also restarted docker. 

Thank you very much for your suggestion! 

Regards,
Rong

**Comment by ryao-mdanderson** [comment]
@vsoch Thanks again, this helps.

The latest version and the newer version v3.8.2 and v3.8.3 are about 2 months ago. Recall my latest successful work was last month 2021.09.14, I guess I have already used one of these version. 
I pulled an older version 3.8.1 and tried the above command again, this time, hit the error:
While performing build: while creating SIF: while creating container: writing data object for SIF file: copying data object file to SIF file: write /tmp/rstudio-4.0.4-20211017-2021-10-18-2142069924bd.sif: no space left on device

This is the same error I saw before I did "docker system prune -a".  I am sorry to bother you, how do I get around to this? 
"df -h" command shows the following, I am puzzled where could be the issue?

 df -h
Filesystem                   Size  Used Avail Use% Mounted on
devtmpfs                      16G     0   16G   0% /dev
tmpfs                         16G     0   16G   0% /dev/shm
tmpfs                         16G  1.8M   16G   1% /run
tmpfs                         16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/VG0-rootlv        10G  8.7G  1.4G  87% /
/dev/mapper/VG0-usrlv         10G  7.8G  2.3G  78% /usr
/dev/sda1                    477M  180M  268M  41% /boot
/dev/mapper/VG0-varlv         60G  3.4G   57G   6% /var
/dev/mapper/VG0-tmplv         10G   34M   10G   1% /tmp
/dev/mapper/VG0-optlv         10G  5.6G  4.5G  56% /opt
/dev/mapper/VG0-homelv        70G   41G   30G  58% /home

**Comment by vsoch** [comment]
You don’t have enough room on your filesystem. Make more room or try somewhere else. I also already suggested pulling directly from a Docker registry.

**Comment by ryao-mdanderson** [comment]
@vsoch

Sure. I will try this. Thanks again for your helps.

**Comment by vsoch** [comment]
```bash
docker tag <your image name> hpcteam/rstudio-4.0.4 
docker push hpcteam/rstudio-4.0.4 
```
And you probably will need to login, docker login.

**Comment by ryao-mdanderson** [comment]
@vsoch: I really appreciate for your quick response.

After I did a tag
$ docker tag rstudio-4.0.4-20211017 hpcteam/rstudio-4.0.4:20211017

I am able to find the new tagged image
[ryao@r1drpswdev3 ~]$ docker images
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
hpcteam/rstudio-4.0.4                    20211017            3a6abac08567        15 hours ago        2.88 GB
rstudio-4.0.4-20211017                   latest              3a6abac08567        15 hours ago        2.88 GB

Then I tried to push 
$ docker push hpcteam/rstudio-4.0.4
The push refers to a repository [registry.access.redhat.com/hpcteam/rstudio-4.0.4]
5fee665b2ff6: Preparing 
2743b040803e: Preparing 
2c991c434766: Preparing 
dac39b3acc9f: Preparing 
b696421832a4: Preparing 
05f3b67ed530: Waiting 
ec1817c93e7c: Waiting 
9e97312b63ff: Waiting 
e1c75a5e0bfa: Waiting 
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;registry&#46;access&#46;redhat&#46;com&#47;v2&#47;hpcteam&#47;rstudio&#45;4&#46;0&#46;4&#47;blobs&#47;uploads&#47;\" on this server.<P>\nReference&#32;&#35;18&#46;85911160&#46;1634587117&#46;3812c44d\n</BODY>\n</HTML>\n"

I noticed that I should I login, so I login docker.io:
$ docker login docker.io
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: hpcteam
Password: 
Login Succeeded
$ docker push hpcteam/rstudio-4.0.4
The push refers to a repository [registry.access.redhat.com/hpcteam/rstudio-4.0.4]
5fee665b2ff6: Preparing 
2743b040803e: Preparing 
2c991c434766: Preparing 
dac39b3acc9f: Preparing 
b696421832a4: Preparing 
05f3b67ed530: Waiting 
ec1817c93e7c: Waiting 
9e97312b63ff: Waiting 
e1c75a5e0bfa: Waiting 
error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;registry&#46;access&#46;redhat&#46;com&#47;v2&#47;hpcteam&#47;rstudio&#45;4&#46;0&#46;4&#47;blobs&#47;uploads&#47;\" on this server.<P>\nReference&#32;&#35;18&#46;7c911160&#46;1634587314&#46;2624f38a\n</BODY>\n</HTML>\n"

Did I ignore anything in this case? I believe the permission repository hpcteatm/rstudio-4.0.4 in https://hub.docker.com/repositories is public.

**Comment by ryao-mdanderson** [comment]
@vsoch 👍 awesome.

Followed your suggestion I tag the image with docker.io and redo the push, it works. Thank you very much for your help.
I guess docker was installed on the system by an rpm provided by redhat, thus it access registry.access.redhat.com by default.

**Comment by vsoch** [comment]
Yep sure thing! Glad it worked. For the future, when you need this kind of back and forth support I recommend a Singularity slack - there are two now :)

**Comment by vsoch** [comment]
Thanks! Closing the issue since we got you settled. Have a good one!
