### ISSUE TITLE
Is it possible to run this in a github action

### ISSUE THREAD

**Issue by alexlenail** [singularityhub/docker2singularity#121]
Would love to see documentation for how to configure a github action to build a singularity image from a dockerfile and upload it to the singularity hub.

**Comment by vsoch** [comment]
Singularity Hub hasn’t been in operation since 2020 (it’s an archive) but there’s a much easier way - push a SIF directly to packages and pull with singularity via ORAS: 

https://github.com/singularityhub/github-ci

**Comment by vsoch** [comment]
And if you truly want Dockerfile -> Singularity build, express your interest here! https://github.com/sylabs/singularity/pull/889

I opened the PR about a week ago and we need to figure out how it best fits into future refactors with a different runtime.

Closing issue, please comment / re-open if I haven't answered your question, or if you want to chat further!
