### ISSUE TITLE
Template parsing error

### ISSUE THREAD

**Issue by wt12318** [singularityhub/docker2singularity#126]
Hi friend, what is your question?

I installed the singularity using Conda, and use this tools to convert my docker image:

```
docker run \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /home/data_backup1/homelette/singularity_image:/output \
--privileged -t --rm \
quay.io/singularity/docker2singularity  \
homelette
```

But I got the error: 

```
Image Format: squashfs
Docker Image: homelette

Template parsing error: template: :1:2: executing "" at <.Size>: map has no entry for key "Size"
```

How could I fix this problem?

**Comment by vsoch** [comment]
I'm not sure how you are using a singularity conda install with this container - but generally the best practice to convert docker to singularity is just to pull directly,e.g., `singularity pull docker://ubuntu`

**Comment by wt12318** [comment]
Hi,

I used Conda to install singularity, and construct the docker image from : https://github.com/PhilippJunk/homelette/blob/master/docker/construct_local_image.sh (`docker pull philippjunk/homelette_template` ) and then want to use the `docker2singularity` to convert this image to singularity  image, but the error occur.

**Comment by vsoch** [comment]
Yes so instead you should singularity pull from Docker directly.

**Comment by wt12318** [comment]
Thank you. I got it.
