### ISSUE TITLE
I got error a conversion from Docker image to Singularity. How to resolve it??

### ISSUE THREAD

**Issue by Soratake-HirotakaYajima** [singularityhub/docker2singularity#133]
I am performing a conversion from a 

Docker image to Singularity.

However, I am unable to do so due to an error like below. Any advice would be appreciated!
 I use Mac and Docker desktop.

`$ docker run --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/out_sif:/output --privileged -t --rm quay.io/singularity/docker2singularity ubuntu:14.04`

Image Format: squashfs
Docker Image: ubuntu:14.04

Inspected Size: 188 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
(3/10) Creating labels...
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_respond: symbol not found
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_alloc: symbol not found
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_free: symbol not found
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_receive: symbol not found
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_fd: symbol not found
Error relocating /usr/local/singularity/bin/singularity: seccomp_notify_id_valid: symbol not found

**Comment by vsoch** [comment]
If you want to convert docker to singularity, you no longer need this tool. Just do:

```bash
singularity pull docker://<uri>
```

**Comment by Soratake-HirotakaYajima** [comment]
Doesn't this tool convert Docker images to singularity images?

**Comment by vsoch** [comment]
If you want to use the tool for a one-off conversion like that, I can look into the issue. I'm finishing up dinner but will soon. It looks to be a missing library - I'll see if I can reproduce.

**Comment by Soratake-HirotakaYajima** [comment]
Thank you so much

**Comment by vsoch** [comment]
@Soratake-HirotakaYajima this morning I built a new release: `quay.io/singularity/docker2singularity:latest` and here is my suggestion. That image has singularity 4.1.4 and I also added the development headers of that library mentioned. Give that a try. If it doesn't work, please shell into the container interactively and try doing something else with Singularity (a singularity run of a docker uri would suffice) to see if you can reproduce the issue. If you can, then please try doing the same run in one of the images here: https://quay.io/repository/singularity/singularity. The main difference is that they are built with an ubuntu base (vs. here is alpine), so we can rule that out. Hopefully some of the above investigation can help shed some light on the issue. Thanks!

**Comment by Soratake-HirotakaYajima** [comment]
別のエラーが発生しました

% docker run --platform linux/amd64 -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/out_sif:/output --privileged -t --rm quay.io/singularity/docker2singularity ubuntu:14.04

Image Format: squashfs
Docker Image: ubuntu:14.04

Inspected Size: 188 MB

(1/10) Creating a build sandbox...
(2/10) Exporting filesystem...
(3/10) Creating labels...
(4/10) Adding run script...
  File "<string>", line 1
    import json, pipes, sys; print " ".join(pipes.quote(a) for a in json.load(sys.stdin) or [])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
(base) yazimahitotaka (arm64):~/Projects/digzyme/MEMO/docker

**Comment by vsoch** [comment]
That's a python error (python3 from python 2).

**Comment by vsoch** [comment]
When this build is done, try re-pulling and try again:

https://github.com/singularityhub/docker2singularity/actions/runs/10156616976

**Comment by Soratake-HirotakaYajima** [comment]
Success conversion docker to singularity image !!
Thank you so much your effort!!

**Comment by vsoch** [comment]
Wonderful! Thank you for reporting the issue! I'm going to close it, and please ping again if something arises.
