### ISSUE TITLE
Building ppc images on x86 hardware

### ISSUE THREAD

**Issue by wrathematics** [singularityhub/docker2singularity#90]
I need to create a Singularity container for Summit, a ppc system. I do not have root on power hardware, so I am building the container in docker with qemu, and then trying to convert via docker2singuarity:

```
sudo docker run -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/test:/output --privileged -t --rm \
  singularityware/docker2singularity \
  my-image
```

I have done this successfully in the past (~2 years ago), but it no longer works as I expect. The Singularity image is amd64, even though it contains ppc64le software. My best guess is that this is due to a change in Singularity itself, although I don't actually know what is going on.

Using docker2singularity, is there any way to force the Singularity image to be ppc64le?

**Comment by vsoch** [comment]
hey @wrathematics! I don’t know the answer to your question, but if you want to ask the folks at Sylabs and report back here I’d be happy to do any updates to the code or docs to help you out.

**Comment by wrathematics** [comment]
Will do. Thanks.
