### ISSUE TITLE
Error when I try to run a container - ABORT  : Retval = 255

### ISSUE THREAD

**Issue by camilomarino** [singularityhub/docker2singularity#97]
I have a problem trying to run any Singularity image created with docker2singularity.
As an example, when converting the following image:
```
  docker run -v /var/run/docker.sock:/var/run/docker.sock \
            -v / tmp / test: / output \
            --privileged -t --rm \
            quay.io/singularity/docker2singularity \
            ubuntu: 14.04
```
The image is created correctly, but when executing:
```
singularity shell /tmp/test/ubuntu_14.04-2020-09-16-119fd5e2c6ae.sif
```
I get the following error:
```
ERROR  : Unknown image format/type: /tmp/test/ubuntu_14.04-2020-09-16-119fd5e2c6ae.sif
ABORT  : Retval = 255
```
The same happens when using the commands: exec, inspect and run.

When trying different alternatives, I found that converting the image with the -f option (as folder) does not produce an error. However, this is not practical, because a new conversion to the ".sif" format is required and for images of several GB it takes a long time.

**Comment by vsoch** [comment]
What version of Singularity do you have locally? I think what is likely happening is that you have a version that is not compatible with the one you are building. For example, I have:

```bash
$ singularity --version
singularity version 3.6.3+108-gb536fb69c
```

I can run the same command as you:

```bash
mkdir -p /tmp/test
$ docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm quay.io/singularity/docker2singularity ubuntu:14.04
```

And then I can interact with the container without issue:

```bash
$ singularity shell /tmp/test/ubuntu_14.04-2020-09-16-ce0a20675645.sif 
Singularity> 
```
So I would look at the version of Singularity you have, and try the container on Quay.io tagged with the closest to it. https://quay.io/repository/singularity/docker2singularity?tab=tags

**Comment by camilomarino** [comment]
Thank you very much for the quick reply. My version of singularity is "2.6.1-dist", because this is the version installed in the cluster that I use.

I hadn't realized that it was necessary to tag the Singularity version.

In short, the following creates a fully functional image for me:
```
  docker run -v /var/run/docker.sock:/var/run/docker.sock \
            -v / tmp / test: / output \
            --privileged -t --rm \
            quay.io/singularity/docker2singularity:v2.6 \
            ubuntu: 14.04
```

**Comment by vsoch** [comment]
Great! Yeah we didn't see the sif format until maybe 3? So it's understandable that it didn't work. I'm glad that you found the right container, I'll close the issue and please let me know if you have any other questions.
